version: '3.8'
services:
  arma3:
    build: .
    platform: linux/amd64
    container_name: arma3
#    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - './missions:/arma3/mpmissions'
      - './configs:/arma3/configs'
      - './mods:/arma3/mods'
      - './servermods:/arma3/servermods'
    restart: unless-stopped